kind: Service
apiVersion: v1
metadata:
  name: zipkin
spec:
  selector:
    app: zipkin
  ports:
    - port: 9411
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: zipkin
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /zipkin
            backend:
              serviceName: zipkin
              servicePort: 9411
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
spec:
  selector:
    matchLabels:
      app: zipkin
  #  replicas: 1
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9411
          livenessProbe:
            httpGet:
              path: /zipkin
              port: 9411
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /zipkin
              port: 9411
            initialDelaySeconds: 3
            periodSeconds: 3
