spring:
  zipkin:
    base-url: http://simplest-collector:9411
  data:
    mongodb:
      host: env-mongodb
      port: 27017
      database: demo
      username: username
      password: password
server:
  port: 80
