spring:
  zipkin:
    base-url: http://zipkin:9411
  data:
    mongodb:
      host: mongo
      port: 27017
  cloud:
    kubernetes:
      discovery:
        enabled: false
      ribbon:
        enabled: false
management:
  metrics:
    export:
      influx:
        uri: http://localhost:8086
        db: k8s
server:
  port: 80
springdoc:
  server:
    base-url: http://localhost:8003
kunde-service:
  ribbon:
    listOfServers: kunde-service
produkt-service:
  ribbon:
    listOfServers: produkt-service
