spring:
  zipkin:
    base-url: http://simplest-collector:9411
  data:
    mongodb:
      host: env-mongodb
      port: 27017
      database: demo
      username: username
      password: password
management:
  metrics:
    export:
      influx:
        uri: http://monitoring-influxdb.kube-system:8086
        db: k8s
        user-name: root
        password: root
server:
  port: 8080
springdoc:
  server:
    base-url: https://localhost/swagger-ui
feign:
  kunde-service: http://kunde-service:8080
  produkt-service: http://produkt-service:8080
