spring:
  zipkin:
    base-url: http://simplest-collector:9411
  data:
    mongodb:
      host: env-mongodb
      port: 27017
      database: demo
      username: username
      password: password
  cloud:
    kubernetes:
      discovery:
        enabled: true
      ribbon:
        enabled: true
        mode: SERVICE
management:
  metrics:
    export:
      influx:
        uri: http://monitoring-influxdb.kube-system:8086
        db: k8s
        user-name: root
        password: root
server:
  port: 80
springdoc:
  server:
    base-url: https://localhost
