spring:
  zipkin:
    base-url: http://zipkin:9411
  data:
    mongodb:
      host: mongo
      port: 27017
  cloud:
    kubernetes:
      discovery:
        enabled: false
      ribbon:
        enabled: false
server:
  port: 80
kunde-service:
  ribbon:
    listOfServers: kunde-service
preis-service:
  ribbon:
    listOfServers: preis-service
produkt-service:
  ribbon:
    listOfServers: produkt-service
