spring:
  zipkin:
    base-url: http://localhost:9411
  data:
    mongodb:
      host: localhost
      port: 27017
  cloud:
    kubernetes:
      discovery:
        enabled: false
      ribbon:
        enabled: false
management:
  metrics:
    export:
      influx:
        uri: http://localhost:8086
        db: k8s
server:
  port: 8003
springdoc:
  server:
    base-url: http://localhost:8003
kunde-service:
  ribbon:
    listOfServers: localhost:8001
produkt-service:
  ribbon:
    listOfServers: localhost:8002
