spring:
  application:
    name: rechnung-service
  output:
    ansi:
      enabled: always
  sleuth:
    sampler:
      probability: 1
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
    mongo:
      enabled: true
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: true
server:
  servlet:
    context-path: /rechnung-api
logging:
  level:
    root: INFO
    com.example: DEBUG
springdoc:
  show:
    actuator: true
