version: "3.5"
services:

  configuration-service:
    build: ./configuration-service
    restart: always
    ports:
      - 8888:8888

  discovery-service:
    build: ./discovery-service
    restart: always
    ports:
      - 8761:8761
    environment:
      - SPRING_PROFILES_ACTIVE=demo
    depends_on:
      - configuration-service

  kunde-service:
    build: ./kunde-service
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=demo
    depends_on:
      - configuration-service
      - discovery-service

  preis-service:
    build: ./preis-service
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=demo
    depends_on:
      - configuration-service
      - discovery-service

  produkt-service:
    build: ./produkt-service
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=demo
    depends_on:
      - configuration-service
      - discovery-service

  rechnung-service:
    build: ./rechnung-service
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=demo
    depends_on:
      - configuration-service
      - discovery-service
      - kunde-service
      - preis-service
      - produkt-service

  gateway-service:
    build: ./gateway-service
    restart: always
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=demo
    depends_on:
      - configuration-service
      - discovery-service
      - kunde-service
      - preis-service
      - produkt-service
      - rechnung-service
