version: "3.5"
services:

  mongo:
    image: mongo
    ports:
      - 27017:27017

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

#  sonarqube:
#    image: sonarqube
#    ports:
#      - 9000:9000
