apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: zipkin
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /zipkin
            backend:
              serviceName: zipkin
              servicePort: 9411
