spring:
  application:
    name: kunde-service
  output:
    ansi:
      enabled: always
  sleuth:
    sampler:
      probability: 1
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    username: username
    password: password
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
server:
  servlet:
    context-path: /kunde-api
logging:
  level:
    root: INFO
    com.example: DEBUG
springdoc:
  show:
    actuator: true

---
spring:
  profiles: default
  zipkin:
    base-url: http://localhost:9411
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
server:
  port: 8001

---
spring:
  profiles: docker
  zipkin:
    base-url: http://zipkin:9411
  datasource:
    url: jdbc:postgresql://postgres:5432/demo
server:
  port: 80

---
spring:
  profiles: kubernetes
  zipkin:
    base-url: http://simplest-collector:9411
  datasource:
    url: jdbc:postgresql://env-postgresql:5432/demo
server:
  port: 80
