spring:
  zipkin:
    base-url: http://simplest-collector:9411
  datasource:
    url: jdbc:postgresql://env-postgresql:5432/demo
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
server:
  port: 80
springdoc:
  server:
    base-url: https://localhost
