spring:
  zipkin:
    base-url: http://simplest-collector:9411
  datasource:
    url: jdbc:postgresql://env-postgresql:5432/demo
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
management:
  metrics:
    export:
      influx:
        uri: http://monitoring-influxdb.kube-system:8086
        db: k8s
        user-name: root
        password: root
server:
  port: 80
springdoc:
  server:
    base-url: https://localhost

