spring:
  zipkin:
    base-url: http://zipkin:9411
  datasource:
    url: jdbc:postgresql://postgres:5432/demo
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
management:
  metrics:
    export:
      influx:
        uri: http://localhost:8086
        db: k8s
server:
  port: 80
springdoc:
  server:
    base-url: http://localhost:8001
