server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS
logging:
  level:
    com.example.gatewayservice: DEBUG
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  sleuth:
    sampler:
      probability: 1
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: kunde-route
          uri: lb://kunde-service
          predicates:
            - Path=/kunden/**
        - id: produkt-route
          uri: lb://produkt-service
          predicates:
            - Path=/produkte/**
        - id: preis-route
          uri: lb://preis-service
          predicates:
            - Path=/preise/**
        - id: rechnung-route
          uri: lb://rechnung-service
          predicates:
            - Path=/rechnungen/**
