spring:
  sleuth:
    sampler:
      probability: 1
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: username
    password: password
management:
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
    mongo:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 0
logging:
  level:
    root: INFO
    com.example: DEBUG
