spring:
  zipkin:
    base-url: http://zipkin:9411
  datasource:
    url: jdbc:postgresql://postgres:5432/demo
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
