spring:
  sleuth:
    sampler:
      probability: 1
management:
  endpoint:
    health:
      show-details: always
    web:
      exposure:
        include: refresh
  health:
    defaults:
      enabled: true
    mongo:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 0
logging:
  level:
    root: INFO
    com.example.rechnungservice: DEBUG
