apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{.Chart.Name}}
spec:
  rules:
    - http:
        paths:
          - path: /{{regexReplaceAllLiteral "service" .Chart.Name "api"}}
            backend:
              serviceName: {{.Chart.Name}}
              servicePort: {{.Values.port}}
