version: "3.5"
services:

  kunde-service:
    image: localhost:32000/demo/kunde-service:latest
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8001:80

  produkt-service:
    image: localhost:32000/demo/produkt-service:latest
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8002:80

  rechnung-service:
    image: localhost:32000/demo/rechnung-service:latest
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8003:80
    depends_on:
      - kunde-service
      - produkt-service

networks:
  default:
    external:
      name: env_default
