apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  #  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
          livenessProbe:
            exec:
              command: ["mongo", "--eval", "db.adminCommand('ping')"]
          readinessProbe:
            exec:
              command: ["mongo", "--eval", "db.adminCommand('ping')"]
